# Ref:- https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service: synchronizeservers
 
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: ap-southeast-1
  stackName: ${self:service}-${self:provider.stage}-template
  apiName: api-${self:service}
  memorySize: 512
  deploymentBucket:
    name: com.serverless.infraguard.${self:provider.region}.deploys
    serverSideEncryption: AES256      
        
iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "SES:SendEmail"
      - "SES:SendRawEmail"
    Resource: "*"

functions:
  syncPlatformServers:
    handler: app.server # reference the file and exported method  
    role: ${file(env.yml):${self:provider.stage}.ROLE_ARN}
    description: This function will run the script management policies on the production environment.
    name: ${self:provider.stage}-${self:service} # optional, Deployed Lambda name
    timeout: 900   
    environment: # add environment property
        APP_STAGE: ${opt:stage}   
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true